version: "3"

services:
  client:
    build: client/
    image: client
    container_name: client
    user: 1234:1234
    ports:
    -  "8000:8000"
    networks:
      -  project
    depends_on:
      -  server
  server:
    build: server/
    image: server
    container_name: server
    user: 1234:1234
    restart: always
    environment:
      port: 6000
    ports:
    -  "0.0.0.0:8001:6000"
    volumes:
      -  /home/kali/Downloads:/data:ro
    networks:
      -  project
networks:
  project:
    driver: bridge
